spring.datasource.url=jdbc:mysql://localhost:3306/GestioneProdotti
spring.datasource.username=root
spring.datasource.password=Vincenzo2002!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true