spring.application.name=hogwartsos
spring.datasource.url=jdbc:mysql://localhost:3306/hogwartsosSpring
spring.datasource.username=root
spring.datasource.password=Vincenzo2002!
spring.jpa.hibernate.ddl-auto=update